[book]
authors = ["Claudio"]
language = "it"
multilingual = false
src = "src"
title = "Informatica - Quinto anno - Materiale didattico"

[build]
build-dir = "docs"
create-missing = true

[output.html]
additional-css = ["custom.css"]
git-repository-url = "https://github.com/wbigger/book-cs-5y-2021.git"